<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit4b87608fd3ec7f7a7d2ff04eabc31f0f
{
    public static $files = array (
        '9e4824c5afbdc1482b6025ce3d4dfde8' => __DIR__ . '/..' . '/league/csv/src/functions_include.php',
    );

    public static $prefixLengthsPsr4 = array (
        'N' => 
        array (
            'Nolan_Group\\' => 12,
        ),
        'L' => 
        array (
            'League\\Csv\\' => 11,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Nolan_Group\\' => 
        array (
            0 => __DIR__ . '/../..' . '/core',
        ),
        'League\\Csv\\' => 
        array (
            0 => __DIR__ . '/..' . '/league/csv/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit4b87608fd3ec7f7a7d2ff04eabc31f0f::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit4b87608fd3ec7f7a7d2ff04eabc31f0f::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit4b87608fd3ec7f7a7d2ff04eabc31f0f::$classMap;

        }, null, ClassLoader::class);
    }
}
