<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Nolan_Group\\' => array($baseDir . '/core'),
    'League\\Csv\\' => array($vendorDir . '/league/csv/src'),
);
